/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as CollectionsSlugIndexRouteImport } from './routes/collections.$slug.index'
import { Route as CollectionsSlugProductSlugRouteImport } from './routes/collections.$slug.$productSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugIndexRoute = CollectionsSlugIndexRouteImport.update({
  id: '/collections/$slug/',
  path: '/collections/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugProductSlugRoute =
  CollectionsSlugProductSlugRouteImport.update({
    id: '/collections/$slug/$productSlug',
    path: '/collections/$slug/$productSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/collections/$slug/$productSlug': typeof CollectionsSlugProductSlugRoute
  '/collections/$slug/': typeof CollectionsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/services': typeof ServicesIndexRoute
  '/collections/$slug/$productSlug': typeof CollectionsSlugProductSlugRoute
  '/collections/$slug': typeof CollectionsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/collections/$slug/$productSlug': typeof CollectionsSlugProductSlugRoute
  '/collections/$slug/': typeof CollectionsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery/$slug'
    | '/services/$slug'
    | '/collections/'
    | '/gallery/'
    | '/services/'
    | '/collections/$slug/$productSlug'
    | '/collections/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery/$slug'
    | '/services/$slug'
    | '/collections'
    | '/gallery'
    | '/services'
    | '/collections/$slug/$productSlug'
    | '/collections/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery/$slug'
    | '/services/$slug'
    | '/collections/'
    | '/gallery/'
    | '/services/'
    | '/collections/$slug/$productSlug'
    | '/collections/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GallerySlugRoute: typeof GallerySlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  CollectionsSlugProductSlugRoute: typeof CollectionsSlugProductSlugRoute
  CollectionsSlugIndexRoute: typeof CollectionsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug/': {
      id: '/collections/$slug/'
      path: '/collections/$slug'
      fullPath: '/collections/$slug/'
      preLoaderRoute: typeof CollectionsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug/$productSlug': {
      id: '/collections/$slug/$productSlug'
      path: '/collections/$slug/$productSlug'
      fullPath: '/collections/$slug/$productSlug'
      preLoaderRoute: typeof CollectionsSlugProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GallerySlugRoute: GallerySlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  CollectionsSlugProductSlugRoute: CollectionsSlugProductSlugRoute,
  CollectionsSlugIndexRoute: CollectionsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
